name: Stream Trigger

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL ya poora Iframe Code daalein'
        required: true
        type: string
      okru_stream_channel:
        description: 'Stream Channel ID (1 to 8)'
        required: true
        default: '1'
        type: string
      stream_quality:
        description: 'Quality Settings'
        required: true
        default: '110KBps (Balanced 480p)'
        type: string

jobs:
  start-stream:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # YAHAN TABDEELI KI GAYI HAI 👇
      # Hum NPM ko bata rahe hain ke Chromium browser download MAt karo,
      # taake installation hang na ho.
      - name: Install Dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true 
        run: npm install

      # YAHAN BHI TABDEELI KI GAYI HAI 👇
      # Hum Linux ka default Chromium browser install kar rahe hain jo tez hota hai.
      - name: Install System Utilities (FFmpeg, Xvfb, Audio, Browser)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb pulseaudio ffmpeg dbus-x11 chromium-browser

      - name: Run Live Stream
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
          OKRU_STREAM_ID: ${{ github.event.inputs.okru_stream_channel }}
          STREAM_QUALITY: ${{ github.event.inputs.stream_quality }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISPLAY: :99
          # Puppeteer ko bata rahe hain ke konsa browser use karna hai
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser 
        run: |
          # 1. Virtual Audio Device start karna
          pulseaudio -D --exit-idle-time=-1
          pacmd load-module module-virtual-sink sink_name=v1
          
          # 2. Virtual Display start karna
          Xvfb :99 -screen 0 1280x720x24 &
          
          # 3. Thoda wait aur phir script start karna
          sleep 3
          node stream.js
